# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/3C7/LabE/LabE/LabE.cache/wt [current_project]
set_property parent.project_path Z:/3C7/LabE/LabE/LabE.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo z:/3C7/LabE/LabE/LabE.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  Z:/3C7/LabC/LabC-20190212T152347Z-001/LabC/full_adder.v
  Z:/3C7/LabC/LabC-20190212T152347Z-001/LabC/6bit_ripple_adder.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc Z:/3C7/LabE/adder.xdc
set_property used_in_implementation false [get_files Z:/3C7/LabE/adder.xdc]

read_xdc Z:/3C7/LabE/LabE/LabE.srcs/constrs_1/new/Ripple_Adder.xdc
set_property used_in_implementation false [get_files Z:/3C7/LabE/LabE/LabE.srcs/constrs_1/new/Ripple_Adder.xdc]


synth_design -top Ripple_Adder -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Ripple_Adder.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Ripple_Adder_utilization_synth.rpt -pb Ripple_Adder_utilization_synth.pb"
