webtalk_init -webtalk_dir /home/cmcnally/Documents/Year5/Semester 2/5M9/Labs/Lab1/CMcnally_Lab1_FSM/CMcnally_Lab1_FSM.sim/sim_1/behav/xsim/xsim.dir/fsm_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb 12 18:46:24 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a4ca29ae-5eb5-48a8-b75f-9f3a3f37b991" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "27df75f50b5c430ebf4ad174cd836eda" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3263.186 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "270 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125596_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1170044717 -regid "" -xml /home/cmcnally/Documents/Year5/Semester 2/5M9/Labs/Lab1/CMcnally_Lab1_FSM/CMcnally_Lab1_FSM.sim/sim_1/behav/xsim/xsim.dir/fsm_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/cmcnally/Documents/Year5/Semester 2/5M9/Labs/Lab1/CMcnally_Lab1_FSM/CMcnally_Lab1_FSM.sim/sim_1/behav/xsim/xsim.dir/fsm_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/cmcnally/Documents/Year5/Semester 2/5M9/Labs/Lab1/CMcnally_Lab1_FSM/CMcnally_Lab1_FSM.sim/sim_1/behav/xsim/xsim.dir/fsm_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
