# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/cmcnally/Repos/digital-design-projects/integrated-systems-design/FIR_Filter_Implimentation/FIR_Filter/FIR_Filter.cache/wt [current_project]
set_property parent.project_path /home/cmcnally/Repos/digital-design-projects/integrated-systems-design/FIR_Filter_Implimentation/FIR_Filter/FIR_Filter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo /home/cmcnally/Repos/digital-design-projects/integrated-systems-design/FIR_Filter_Implimentation/FIR_Filter/FIR_Filter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/cmcnally/Repos/digital-design-projects/integrated-systems-design/FIR_Filter_Implimentation/FIR_Filter/FIR_Filter.srcs/sources_1/imports/Lab4/measure_sine_peak.sv
  /home/cmcnally/Repos/digital-design-projects/integrated-systems-design/FIR_Filter_Implimentation/FIR_Filter/FIR_Filter.srcs/sources_1/imports/Lab4/sig_gen.sv
  /home/cmcnally/Repos/digital-design-projects/integrated-systems-design/FIR_Filter_Implimentation/FIR_Filter/FIR_Filter.srcs/sources_1/imports/Lab4/fir_filter_test.sv
}
read_ip -quiet /home/cmcnally/Repos/digital-design-projects/integrated-systems-design/FIR_Filter_Implimentation/FIR_Filter/FIR_Filter.srcs/sources_1/ip/cordic_0/cordic_0.xci
set_property used_in_implementation false [get_files -all /home/cmcnally/Repos/digital-design-projects/integrated-systems-design/FIR_Filter_Implimentation/FIR_Filter/FIR_Filter.srcs/sources_1/ip/cordic_0/cordic_0_ooc.xdc]

read_ip -quiet /home/cmcnally/Repos/digital-design-projects/integrated-systems-design/FIR_Filter_Implimentation/FIR_Filter/FIR_Filter.srcs/sources_1/ip/fir_compiler_0_1/fir_compiler_0.xci
set_property used_in_implementation false [get_files -all /home/cmcnally/Repos/digital-design-projects/integrated-systems-design/FIR_Filter_Implimentation/FIR_Filter/FIR_Filter.srcs/sources_1/ip/fir_compiler_0_1/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/cmcnally/Repos/digital-design-projects/integrated-systems-design/FIR_Filter_Implimentation/FIR_Filter/FIR_Filter.srcs/sources_1/ip/fir_compiler_0_1/fir_compiler_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/cmcnally/Repos/digital-design-projects/integrated-systems-design/FIR_Filter_Implimentation/FIR_Filter/FIR_Filter.srcs/constrs_1/imports/Lab3/Basys3_Master.xdc
set_property used_in_implementation false [get_files /home/cmcnally/Repos/digital-design-projects/integrated-systems-design/FIR_Filter_Implimentation/FIR_Filter/FIR_Filter.srcs/constrs_1/imports/Lab3/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fir_filter_test -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fir_filter_test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fir_filter_test_utilization_synth.rpt -pb fir_filter_test_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
